name: Push to Netcup 
run-name: pushes the vcard to netcup test
on:
  push:
    branches:
      - develop

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Rename src
        run: cp -a src test
      - name: copy dir via ssh
        uses: appleboy/scp-action@master
        with:
          host: "188.68.47.208"
          username: hosting126902
          key: ${{ secrets.NETCUP }}
          port: "22"
          source: "test"
          target: "cbackes.me/httpdocs"
          rm: true